In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [268]:
df = pd.read_csv("../Downloads/agriculture_dataset.csv")

In [269]:
df

High_Resolution_RGB  Multispectral_Images  Thermal_Images  \
0                         0                     0               0   
1                         1                     1               0   
2                         0                     0               0   
3                         0                     0               0   
4                         0                     1               1   
...                     ...                   ...             ...   
212014                    0                     0               0   
212015                    0                     0               0   
212016                    0                     0               0   
212017                    0                     0               0   
212018                    0                     0               0   

        Temporal_Images  Spatial_Resolution  GPS_Coordinates  \
0                     0            0.667324           201538   
1                     0            1.459000           215854   
2                     0            0.500442           890802   
3                     0            1.865161           605584   
4                     1            1.392331           871732   
...                 ...                 ...              ...   
212014                0            1.613700           257270   
212015                0            2.167963           875693   
212016                0            1.553286           159572   
212017                0            1.550687           859553   
212018                0            1.409110           910100   

        Field_Boundaries  Elevation_Data  Canopy_Coverage      NDVI  ...  \
0                      3       28.207634         8.046926  0.676945  ...   
1                      3       82.335147       147.512332  0.414781  ...   
2                      3       83.865629        30.246527  0.723610  ...   
3                      3       20.747905         6.857820  0.405611  ...   
4                      3       22.588815        26.168558  0.465992  ...   
...                  ...             ...              ...       ...  ...   
212014                 3       99.854648        39.864640  0.460258  ...   
212015                 3       41.523453        20.314558  0.196781  ...   
212016                 3       40.316397       149.342415  0.455641  ...   
212017                 3       25.684100        21.912619  0.243414  ...   
212018                 2       98.958476       104.490379  0.571688  ...   

        Weed_Coverage  Pest_Damage  Crop_Growth_Stage  Expected_Yield  \
0            1.922274           84                  2     2540.784327   
1            4.851381           56                  3     3227.617025   
2            5.974859           38                  1     4609.938146   
3            2.100598           27                  2     1409.716754   
4            3.025669           84                  4     3905.312588   
...               ...          ...                ...             ...   
212014       2.406950            5                  2     2974.199519   
212015       2.443758           38                  2     3134.666651   
212016       1.394352           37                  3     3770.711312   
212017       4.573550            2                  1     3263.395842   
212018       0.928552           30                  2     3760.457624   

        Crop_Type  Ground_Truth_Segmentation  Bounding_Boxes  Water_Flow  \
0           Wheat                          1               5   41.771884   
1           Wheat                          0               1   27.564635   
2           Maize                          1               8   29.510836   
3           Maize                          0               1   34.822855   
4            Rice                          0               2   15.493255   
...           ...                        ...             ...         ...   
212014      Maize                          0               8   45.866021   
212015      

In [270]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212019 entries, 0 to 212018
Data columns (total 32 columns):
 #   Column                     Non-Null Count   Dtype  
---  ------                     --------------   -----  
 0   High_Resolution_RGB        212019 non-null  int64  
 1   Multispectral_Images       212019 non-null  int64  
 2   Thermal_Images             212019 non-null  int64  
 3   Temporal_Images            212019 non-null  int64  
 4   Spatial_Resolution         212019 non-null  float64
 5   GPS_Coordinates            212019 non-null  int64  
 6   Field_Boundaries           212019 non-null  int64  
 7   Elevation_Data             212019 non-null  float64
 8   Canopy_Coverage            212019 non-null  float64
 9   NDVI                       212019 non-null  float64
 10  SAVI                       212019 non-null  float64
 11  Chlorophyll_Content        212019 non-null  float64
 12  Leaf_Area_Index            212019 non-null  float64
 13  Crop_Stress_Indicator      21

In [271]:
df.isnull().sum()

High_Resolution_RGB          0
Multispectral_Images         0
Thermal_Images               0
Temporal_Images              0
Spatial_Resolution           0
GPS_Coordinates              0
Field_Boundaries             0
Elevation_Data               0
Canopy_Coverage              0
NDVI                         0
SAVI                         0
Chlorophyll_Content          0
Leaf_Area_Index              0
Crop_Stress_Indicator        0
Temperature                  0
Humidity                     0
Rainfall                     0
Wind_Speed                   0
Soil_Moisture                0
Soil_pH                      0
Organic_Matter               0
Pest_Hotspots                0
Weed_Coverage                0
Pest_Damage                  0
Crop_Growth_Stage            0
Expected_Yield               0
Crop_Type                    0
Ground_Truth_Segmentation    0
Bounding_Boxes               0
Water_Flow                   0
Drainage_Features            0
Crop_Health_Label            0
dtype: i

In [272]:


le = LabelEncoder()
df['Crop_Type'] = le.fit_transform(df['Crop_Type'])


In [273]:
from sklearn.model_selection import train_test_split

In [274]:
x = df.drop('Crop_Health_Label', axis =1)

In [275]:
x

High_Resolution_RGB  Multispectral_Images  Thermal_Images  \
0                         0                     0               0   
1                         1                     1               0   
2                         0                     0               0   
3                         0                     0               0   
4                         0                     1               1   
...                     ...                   ...             ...   
212014                    0                     0               0   
212015                    0                     0               0   
212016                    0                     0               0   
212017                    0                     0               0   
212018                    0                     0               0   

        Temporal_Images  Spatial_Resolution  GPS_Coordinates  \
0                     0            0.667324           201538   
1                     0            1.459000           215854   
2                     0            0.500442           890802   
3                     0            1.865161           605584   
4                     1            1.392331           871732   
...                 ...                 ...              ...   
212014                0            1.613700           257270   
212015                0            2.167963           875693   
212016                0            1.553286           159572   
212017                0            1.550687           859553   
212018                0            1.409110           910100   

        Field_Boundaries  Elevation_Data  Canopy_Coverage      NDVI  ...  \
0                      3       28.207634         8.046926  0.676945  ...   
1                      3       82.335147       147.512332  0.414781  ...   
2                      3       83.865629        30.246527  0.723610  ...   
3                      3       20.747905         6.857820  0.405611  ...   
4                      3       22.588815        26.168558  0.465992  ...   
...                  ...             ...              ...       ...  ...   
212014                 3       99.854648        39.864640  0.460258  ...   
212015                 3       41.523453        20.314558  0.196781  ...   
212016                 3       40.316397       149.342415  0.455641  ...   
212017                 3       25.684100        21.912619  0.243414  ...   
212018                 2       98.958476       104.490379  0.571688  ...   

        Pest_Hotspots  Weed_Coverage  Pest_Damage  Crop_Growth_Stage  \
0                   0       1.922274           84                  2   
1                   0       4.851381           56                  3   
2                   0       5.974859           38                  1   
3                   0       2.100598           27                  2   
4                   0       3.025669           84                  4   
...               ...            ...          ...                ...   
212014              0       2.406950            5                  2   
212015              0       2.443758           38                  2   
212016              0       1.394352           37                  3   
212017              0       4.573550            2                  1   
212018              0       0.928552           30                  2   

        Expected_Yield  Crop_Type  Ground_Truth_Segmentation  Bounding_Boxes  \
0          2540.784327          2                          1               5   
1          3227.617025          2                          0               1   
2          4609.938146          0                          1               8   
3          1409.716754          0                          0               1   
4          3905.312588          1                          0               2   
...                ...        ...                        ...             ...   
212014     2974.199519          0                          0            

In [276]:
x = x.astype(float)


In [277]:
y = df['Crop_Health_Label']

In [279]:
x_train ,x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2) 

In [280]:
from sklearn.linear_model import LogisticRegression

In [281]:
model = LogisticRegression()

In [282]:
model.fit(x_train, y_train)


LogisticRegression()

In [283]:
y_pred = model.predict(x_test)

In [284]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [285]:

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.6973398735968305
Confusion Matrix:
 [[    0 12834]
 [    0 29570]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00     12834
           1       0.70      1.00      0.82     29570

    accuracy                           0.70     42404
   macro avg       0.35      0.50      0.41     42404
weighted avg       0.49      0.70      0.57     42404



/home/admin1/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/admin1/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/admin1/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [286]:
nb_model = GaussianNB()
nb_model.fit(x_train, y_train)


GaussianNB()

In [287]:
y_pred = nb_model.predict(x_test)

In [288]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.6973398735968305
Confusion Matrix:
 [[    0 12834]
 [    0 29570]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00     12834
           1       0.70      1.00      0.82     29570

    accuracy                           0.70     42404
   macro avg       0.35      0.50      0.41     42404
weighted avg       0.49      0.70      0.57     42404



/home/admin1/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/admin1/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/admin1/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
svm_model = SVC(kernel='rbf')
svm_model.fit(x_train, y_train)